name: 设备内核构建 - Android 14 (6.1.162)

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build-device-kernel:
    name: 6.1.162-android14-2026-03-SukiSU-KPM
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: android14
      kernel_version: "6.1"
      sub_level: "162"
      os_patch_level: "2026-03"
      ksu_variant: SukiSU
      enable_kernelsu: true
      version: ""
      build_time: ""
      use_zram: false
      use_bbg: false
      use_kpm: "enabled (开启)"
      enable_user_ns: true
      use_rekernel: false
      cve_2026_43499_patch: false
      supp_op: false
      enable_susfs: true
      droidspaces: "off"
      droidspaces_ntsync: false
      artifact_upload_mode: "上传全部"
